config/routes.rb
#-- copyright
# OpenProject My Project Page Plugin
#
# Copyright (C) 2011-2014 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.md for more details.
#++

# re-write
OpenProject::Application.routes.draw do
  # replace the standard overview-page with the my-project-page
  # careful: do not over-match the reserved path like /projects/new or /projects/level_list, see http://rubular.com/r/1uoiXyApCB
  get 'projects/:id', to: "my_projects_overviews#index" ,
                      constraints: { format: :html, id: Regexp.new("(?!(#{Project::RESERVED_IDENTIFIERS.join('|')})$)(\\w|-)+") }




  get  'my_projects_overview/:id/page_layout',                        to: "my_projects_overviews#page_layout",
                                                                      as: :my_projects_overview
  post 'my_projects_overview/:id/page_layout/save_changes',           to: "my_projects_overviews#save_changes"
  post 'my_projects_overview/:id/page_layout/add_block',              to: "my_projects_overviews#add_block"
  put  'my_projects_overview/:id/page_layout/update_custom_element',  to: "my_projects_overviews#update_custom_element"
  get  'my_projects_overview/:id/page_layout/render_attachments',     to: "my_projects_overviews#render_attachments"
  post 'my_projects_overview/:id/page_layout/destroy_attachment',     to: "my_projects_overviews#destroy_attachment"
end

app/controllers/my_projects_overviews_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject My Project Page Plugin
#
# Copyright (C) 2011-2014 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.md for more details.
#++

class MyProjectsOverviewsController < ApplicationController

  menu_item :overview

  before_action :find_project
  before_action :authorize
  before_action :jump_to_project_menu_item, only: :index

  verify xhr: true, only: [:update_custom_element, :render_attachments, :add_block]

  def self.available_blocks
    @available_blocks ||= OpenProject::MyProjectPage.plugin_blocks
  end

  def index
  end

  # User's page layout configuration
  def page_layout
  end

  def update_custom_element
    block_name = params["block_name"]
    block_title = params["block_title_#{block_name}"]
    textile = params["textile_#{block_name}"]

    if params["attachments"]
      # Attach files and save them
      attachments = Attachment.attach_files(overview, params["attachments"])
      unless attachments[:unsaved].blank?
        render text: t(:warning_attachments_not_saved, attachments[:unsaved].size), status: 500
      end
    end

    if overview.save_custom_element(block_name, block_title, textile)
      render(partial: "block_textilizable",
            locals: { project: project,
                      block_title: block_title,
                      block_name: block_name,
                      textile: textile })
   else
     render text: t(:error_textile_not_saved), status: 400
   end
  end

  # Add a block to user's page
  # The block is added on top of the page
  # params[:block] : id of the block to add
  def add_block
    block = params[:block]
    if MyProjectsOverviewsController.available_blocks.keys.include? block
      render partial: "block", locals: { block_name: block, editing: true }
    elsif block == "custom_element"
      render_new_custom_block
    else
      render nothing: true
    end
  end

  ##
  # Handle saving the changes
  def save_changes
    # Save block states
    save_blocks_from_params

    if overview.save
      flash[:notice] = I18n.t(:notice_successful_update)
      redirect_to(action: :index)
    else
      flash[:error] = I18n.t(:error_saving_changes,
                             errors: overview.errors.full_messages.join(', '))
      render :page_layout
    end
  end

  def render_attachments
    render partial: 'page_layout_attachments'
  end

  def destroy_attachment
    if user.allowed_to?(:edit_project, project)
      begin
        att = Attachment.find(params[:attachment_id].to_i)
        overview.attachments.delete(att)
        overview.save
      rescue ActiveRecord::RecordNotFound
      end
    end

    render partial: 'page_layout_attachments'
  end

  helper_method :project,
                :user,
                :overview
  def project
    @project
  end

  def user
    current_user
  end

  def overview
    @overview ||= MyProjectsOverview.find_or_create_by(project_id: project.id)
  end

  private

  def render_new_custom_block
    new_block = overview.new_custom_element
    overview.hidden << new_block
    if overview.save
      render(partial: "block_textilizable",
             locals: { project: project,
                       block_title: l(:label_custom_element),
                       new_block: true,
                       block_name: new_block.first,
                       textile: new_block.last })
    else
      render text: I18n.t(:error_saving_changes, errors: overview.errors.full_messages.join(', ')),
                   status: 500
    end
  end

  ##
  # Given params of the form
  # { top: 'block,block,block', ... }
  # Save the actual block positions, filtering the list doing so.
  def save_blocks_from_params
    custom_elements = overview.custom_elements

    %w(top left right hidden).each do |group|
      active_blocks = param_to_blocks(params[group], custom_elements)
      overview.send("#{group}=", active_blocks)
    end
  end

  ##
  # Returns a list of valid blocks for the given group param
  def param_to_blocks(block_str, custom_elements)
    blocks = []
    block_str.split(',').select do |name|
      if MyProjectsOverviewsController.available_blocks.keys.include?(name)
        blocks << name
      else
        custom = custom_elements.detect {|ary| ary.first == name }
        blocks << custom unless custom.nil?
      end
    end

    blocks
  end

  def default_breadcrumb
    l(:label_overview)
  end

  def jump_to_project_menu_item
    if params[:jump]
      # try to redirect to the requested menu item
      redirect_to_project_menu_item(project, params[:jump]) && return
    end
  end
end

app/helpers/my_projects_overviews_helper.rb
#-- copyright
# OpenProject My Project Page Plugin
#
# Copyright (C) 2011-2015 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.md for more details.
#++

module MyProjectsOverviewsHelper

  def top_fields
    %w(top)
  end

  def middle_fields
    %w(left right)
  end

  def hidden_fields
    %w(hidden)
  end

  def blocks
    @blocks ||= {
      'top' => overview.top,
      'left' => overview.left,
      'right' => overview.right,
      'hidden' => overview.hidden
    }
  end

  def grid_field(name)
    css_classes = %w(block-receiver list-position widget-container) + [name]
    data = {
      dragula: name,
      position: name
    }
    construct_blocks(name: name, css_classes: css_classes, data: data)
  end

  def rendered_field(name)
    construct_blocks(name: name, css_classes: Array(name))
  end

  def block_options
    @block_options = [default_selected_option]
    MyProjectsOverviewsController.available_blocks.each do |k, v|
      @block_options << [l("my.blocks.#{v}", default: [v, v.to_s.humanize]), k]
    end
    @block_options << [l(:label_custom_element), :custom_element]
  end

  def childprojects
    @childprojects ||= project.children.visible
  end

  def recent_news
    @news ||= project
              .news
              .includes([:author, :project])
              .order("#{News.table_name}.created_on DESC")
              .limit(5)
  end



  def attachments
    @attachments = overview.attachments || []
  end

  private

  def default_selected_option
    [
      "--- #{t(:actionview_instancetag_blank_option)} ---",
      '',
      { disabled: true, selected: true }
    ]
  end

  def construct_blocks(opts = {})
    name, css_classes, data = [:name, :css_classes, :data].map { |sym| opts.fetch sym, '' }
    content_tag :div, id: "list-#{name}", class: css_classes, data: data do
      ActiveSupport::SafeBuffer.new(blocks[name].map { |b| construct b }.join)
    end
  end

  def block_available?(block)
    controller.class.available_blocks.keys.include? block
  end

  def construct(block)
    if block.is_a? Array
      return render_textilized block
    end
    if block_available? block
      return render_normal block
    end
  end

  def ajax_url(name)
    url_for controller: '/my_projects_overviews',
            action: 'order_blocks',
            group: name
  end

  def render_textilized(block)
    render partial: 'block_textilizable', locals: {
      block_name: block.first,
      block_title: block[1],
      textile: block.last
    }
  end

  def render_normal(block)
    render partial: 'block', locals: { block_name: block }
  end
end

app/views/my_projects_overviews/_block.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>
<div id="block_<%= block_name %>" class="widget-box" overview-block block-name="<%= block_name %>">

  <% block_name_id = "my_page_#{block_name}_box_actions" %>
  <% content_for block_name_id do %>
    <div class="box-actions">
      <% if User.current.allowed_to?(:edit_project, project) %>
      <a href="javascript:"
         ng-click="$ctrl.remove()"
         ng-show="$ctrl.editing"
         class="icon icon-close remove-block"
         title="<%= t(:button_delete) %>"></a>
      <% end %>
    </div>
  <% end %>

  <div class="handle">
    <%= render partial: "my_projects_overviews/blocks/#{block_name}", locals: { block_name_id: block_name_id } %>
  </div>
</div>

app/views/my_projects_overviews/_block_textilizable.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% new_block ||= local_assigns[:new_block] %>

<div overview-textile-block
     id="block_<%= block_name %>"
     ng-cloak
     class="widget-box block-teaser"
     block-name="<%= block_name %>"
     new-block="<%= !!new_block %>">
  <div class="handle" cg-busy="$ctrl.loadingIndicator">
    <% content_for block_name do %>
      <div id="<%= block_name %>-form-div" class="textile-form-wrapper" ng-show="$ctrl.formVisible">
        <div class="box-actions">
          <a href="javascript:"
             ng-click="$ctrl.toggleEditForm(false)"
             class="icon icon-cancel reset-textilizable"
             title=<%= l(:button_cancel) %>></a>
        </div>
        <%= form_for :overview,
                     url: {action: 'update_custom_element'},
                     method: :put,
                     multipart: true,
                     html: { class: "textile-form", :'ng-submit' => "$ctrl.submitForm($event)" } do |f| %>

          <%= hidden_field_tag 'block_name', block_name %>
          <div class="form--field -required">
            <%= styled_label_tag "block_title_#{block_name}", t('attributes.title') %>
            <div class="form--field-container">
              <%= styled_text_field_tag "block_title_#{block_name}", block_title %>
            </div>
          </div>
          <div class="form--field -required">
            <%= styled_label_tag "textile_#{block_name}", t('info_custom_text') %>
            <div class="form--field-container" ng-non-bindable>
              <%= styled_text_area_tag "textile_#{block_name}", textile.html_safe, cols: 40, rows: 5, class: 'wiki-edit' %>
            </div>
          </div>
          <%= wikitoolbar_for "textile_#{block_name}" %>
          <%= render partial: 'attachments/form' %>
          <%= styled_button_tag l(:button_save),
              id: "#{block_name}-form-submit",
              class: '-highlight' %>
          <a href="javascript:" ng-click="$ctrl.toggleEditForm(false)" class="reset-textilizable button"><%= t(:button_cancel) %></a>
        <% end %>
      </div>
      <div id="<%= block_name %>-preview-div" class="wiki" ng-show="$ctrl.editing">
        <div class="box-actions" ng-hide="$ctrl.formVisible">
          <% unless User.current.anonymous? %>
            <a href="javascript:"
               class="icon icon-edit edit-textilizable"
               ng-click="$ctrl.toggleEditForm(true)"
               title="<%= l(:button_edit) %>"></a>
          <% end %>
          <% if User.current.allowed_to?(:edit_project, project) %>
            <a href="javascript:"
               ng-click="$ctrl.remove()"
               class="icon icon-close remove-block"
               title="<%= t(:button_delete) %>"></a>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="textile-block-body">
      <%= render partial: "textilizable", locals: { block_title: block_title,
                                                    textile: textile,
                                                    block_name: block_name } %>
    </div>
  </div>
</div>

app/views/my_projects_overviews/_list_dynamic.html.erb
<%#-- copyright
OpenProject is a project management system.
Copyright (C) 2012-2017 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
Copyright (C) 2006-2017 Jean-Philippe Lang
Copyright (C) 2010-2013 the ChiliProject Team

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.rdoc for more details.

++#%>

<%

  def render_wp(property, work_package)
    if property.match /cf_(\d+)/
      return work_package.custom_value_for($1).formatted_value
    end

    case property.to_sym
    when :start_date
      format_date(work_package.start_date)
    when :due_date
      format_date(work_package.due_date)
    when :project
      link_to_project(work_package.project)
    when :done_ratio
      progress_bar(work_package.done_ratio, legend: work_package.done_ratio, hide_total_progress: true)
    when :assigned_to
      link_to_user(work_package.assigned_to)
    when :responsible
      link_to_user(work_package.responsible)
    else
      work_package.public_send property
    end
  rescue => e
    "Failed to render: #{e.message}"
  end

  def render_column(name)
    if name.match /cf_(\d+)/
      CustomField.find($1).name
    else
      WorkPackage.human_attribute_name(name)
    end
  rescue => e
    "Failed to render: #{e.message}"
  end
%>

<%
  columns = query.column_names
  work_packages = query.results.work_packages
%>

<% if work_packages && work_packages.any? %>
  <div class="generic-table--container">
    <div class="generic-table--results-container">
      <table class="generic-table work_packages">
        <colgroup>
          <% columns.each do %>
            <col highlight-col>
            <col highlight-col>
            <col highlight-col>
            <col highlight-col>
          <% end %>
        </colgroup>
        <thead>
          <tr>
            <% columns.each do |property, _| %>
            <th>
              <div class="generic-table--sort-header-outer">
                <div class="generic-table--sort-header">
                  <span>
                    <%= render_column(property) %>
                  </span>
                </div>
              </div>
            </th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% work_packages.each do |work_package| %>
            <tr class="work_package_row-<%= h(work_package.id) %>" class="<%= work_package_css_classes(work_package) %>">
              <% columns.each do |property| %>
                <td class="wp-attribute-<%= property %>">
                  <%= render_wp(property, work_package) %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <%=
    title = t("work_packages.list_simple.#{list_for.to_s}.no_results_title_text")

    no_results_box(action_url: work_packages_path,
                   display_action: true,
                   custom_title: title,
                   custom_action_text: t(:label_work_package_view_all))
  %>
<% end %>

app/views/my_projects_overviews/_members.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% users_by_role.keys.sort.each do |role| %>
  <%= role.name == 'Member' ? 'Users' : (h role) %>: <%= users_by_role[role].sort.collect{ |u| link_to_user u }.join("; ").html_safe %>
  <% if users_by_role[role].count < count_users_by_role[role] %>
    <%= l(:'project_page.x_more', :count => count_users_by_role[role] - users_by_role[role].count) %>
  <% end %>
  <br />
<% end %>

app/views/my_projects_overviews/_page_layout_attachments.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% for attachment in attachments %>
  <p><%= link_to_attachment attachment, class: 'icon icon-attachment' -%>
    <%= h(" - #{attachment.description}") unless attachment.description.blank? %>
    <span class="size">(<%= number_to_human_size attachment.filesize %>)</span>
    <%= link_to icon_wrapper('icon-context icon-delete', l(:button_delete)),
        url: { action: 'destroy_attachment', attachment_id: attachment.id, id: project.id },
        remote: true,
        confirm: l(:text_are_you_sure),
        class: 'delete no-decoration-on-hover',
        title: l(:button_delete),
  update: 'page_layout_attachments' %>
  </p>
<% end %>

app/views/my_projects_overviews/_sidebar.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<h3><%=l(:label_my_account)%></h3>

<p><%=l(:field_login)%>: <strong><%= link_to_user(current_user, :format => :username) %></strong><br />
<%=l(:field_created_on)%>: <%= format_time(current_user.created_on) %></p>


<h4><%= l(:label_feeds_access_key) %></h4>

<p>
<% if current_user.rss_token %>
<%= l(:label_feeds_access_key_created_on, distance_of_time_in_words(Time.now, current_user.rss_token.created_on)) %>
<% else %>
<%= l(:label_missing_feeds_access_key) %>
<% end %>
(<%= link_to l(:button_reset), {:action => 'reset_rss_key'}, :method => :post %>)
</p>

<p>
<% if current_user.api_token %>
<%= l(:label_api_access_key_created_on, distance_of_time_in_words(Time.now, current_user.api_token.created_on)) %>
<% else %>
<%= l(:label_missing_api_access_key) %>
<% end %>
(<%= link_to l(:button_reset), {:action => 'reset_api_key'}, :method => :post %>)
</p>
<% end %>

app/views/my_projects_overviews/_textilizable.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<h3 class="widget-box--header" ng-hide="$ctrl.formVisible">
  <span class="widget-box--header-title"><%= block_title || l(:label_custom_element) %></span>
</h3>

<% if defined? block_name %>
  <%= content_for block_name %>
<% end %>

<div class="textile-body" ng-hide="$ctrl.formVisible">
<% if defined? block_name %>
  <div id="<%= block_name %>-text" class="wiki">
    <%= format_text(textile, :object => overview) %>
  </div>
<% else %>
  <%= format_text(textile, :object => overview) %>
<% end %>
</div>

app/views/my_projects_overviews/index.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>
<div class="overview-page">

<% content_for :header_tags do %>
  <%= auto_discovery_link_tag(:atom, {:controller => 'activities',  :action => 'index', :id => @project, :format => 'atom', :key => User.current.rss_key}) %>
  <%= stylesheet_link_tag "my_project_page/my_projects_overview", :media => 'all' %>
<% end %>

<% html_title(t(:label_overview)) -%>

<%#
=begin%>
 <%#= toolbar title: project.name+" "+t(:label_overview) do %>
<%# end %>
<%#
=end%>


<%= toolbar title: project.name+" "+t(:label_overview) do %>
  <% if User.current.allowed_to?(:add_project, nil, global: true) %>
    <li class="toolbar-item">
      <%#= link_to new_project_path,
          { class: 'button -alt-highlight mt-0',
            aria: {label: t(:label_project_new)},
            title: t(:label_project_new)} do %>
        <%#= op_icon('button--icon icon-add') %>
<!--        <span class="button--text">Create New Project</span>-->
      <%# end %>
    </li>
  <% end %>  
<% end %>

<div class="toolbar-subtitle mb-20">
  <span class="project-id">#<%= @project.id %>:</span> Created by <a [href]="url"><%= @project.full_name %></a>.
</div>


<div id="invisible-grid" class="widget-boxes project-overview">
  <% top_fields.each do |f| %>
    <%= rendered_field f %>
  <% end %>
  <div class="grid-block">
    <% middle_fields.each do |f| %>
      <%= rendered_field f %>
    <% end %>
  </div>
</div>
</div>

app/views/my_projects_overviews/page_layout.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>
<% html_title(l(:label_overview)) -%>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag "my_project_page/my_projects_overview", media: 'all' %>
  <% heads_for_wiki_formatter %>
<% end %>

<overview-page-layout>
<%= toolbar title: l(:label_overview) do %>
  <li class="toolbar-item">
    <%= styled_form_tag({action: "add_block"}, id: "add-block-form") do %>
      <%= styled_select_tag 'block',
                     options_for_select(block_options),
                     id: "block-select",
                     class: 'form--select',
                     :'ng-model' => '$ctrl.selectedBlock',
                     :'ng-change' => '$ctrl.handleBlockSelection()'
    %>
    <% end %>
  </li>
  <li class="toolbar-item">
    <%= form_tag({action: "save_changes"}, id: "save-block-form", :'ng-submit' => '$ctrl.handleSaveChanges()') do %>
      <% blocks.keys.each do |f| %>
        <input type="hidden" name="<%= f %>" value="" />
      <% end %>
      <%= submit_tag t(:button_save), class: 'button -alt-highlight' %>
    <% end %>
  </li>
  <li class="toolbar-item">
    <%= link_to t(:button_cancel), {action: 'index'}, class: 'button' %>
  </li>
<% end %>


<div id="my_project_blocks">
  <h3><%=l(:label_visible_elements) %></h3>
  <div id="visible-grid" class="widget-boxes">
    <div class="grid-block">
      <% middle_fields.each do |f| %>
        <%= grid_field f %>
      <% end %>
    </div>

    <% top_fields.each do |f| %>
      <%= grid_field f %>
    <% end %>
  </div>

  <h3><%=l(:label_hidden_elements) %></h3>
  <div class="widget-boxes">
    <% hidden_fields.each do |f| %>
      <%= grid_field f %>
    <% end %>
  </div>

  <h3><%= l(:label_file_plural) %></h3>
  <div class="attachments" id="page_layout_attachments" data-refresh-url="<%= url_for(action: 'render_attachments') %>">
    <%= render(partial: "page_layout_attachments") %>
  </div>
</div>
</overview-page-layout>