config/routes.rb
#-- copyright
# OpenProject My Project Page Plugin
#
# Copyright (C) 2011-2014 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.md for more details.
#++

# re-write
OpenProject::Application.routes.draw do
  # replace the standard overview-page with the my-project-page
  # careful: do not over-match the reserved path like /projects/new or /projects/level_list, see http://rubular.com/r/1uoiXyApCB
  get 'projects/:id', to: "my_projects_overviews#index" ,
                      constraints: { format: :html, id: Regexp.new("(?!(#{Project::RESERVED_IDENTIFIERS.join('|')})$)(\\w|-)+") }




  get  'my_projects_overview/:id/page_layout',                        to: "my_projects_overviews#page_layout",
                                                                      as: :my_projects_overview
  post 'my_projects_overview/:id/page_layout/save_changes',           to: "my_projects_overviews#save_changes"
  post 'my_projects_overview/:id/page_layout/add_block',              to: "my_projects_overviews#add_block"
  put  'my_projects_overview/:id/page_layout/update_custom_element',  to: "my_projects_overviews#update_custom_element"
  get  'my_projects_overview/:id/page_layout/render_attachments',     to: "my_projects_overviews#render_attachments"
  post 'my_projects_overview/:id/page_layout/destroy_attachment',     to: "my_projects_overviews#destroy_attachment"
end

app/controllers/my_projects_overviews_controller.rb
#-- encoding: UTF-8
#-- copyright
# OpenProject My Project Page Plugin
#
# Copyright (C) 2011-2014 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.md for more details.
#++

class MyProjectsOverviewsController < ApplicationController

  menu_item :overview

  before_action :find_project
  before_action :authorize
  before_action :jump_to_project_menu_item, only: :index

  verify xhr: true, only: [:update_custom_element, :render_attachments, :add_block]

  def self.available_blocks
    @available_blocks ||= OpenProject::MyProjectPage.plugin_blocks
  end

  def index
  end

  # User's page layout configuration
  def page_layout
  end

  def update_custom_element
    block_name = params["block_name"]
    block_title = params["block_title_#{block_name}"]
    textile = params["textile_#{block_name}"]

    if params["attachments"]
      # Attach files and save them
      attachments = Attachment.attach_files(overview, params["attachments"])
      unless attachments[:unsaved].blank?
        render text: t(:warning_attachments_not_saved, attachments[:unsaved].size), status: 500
      end
    end

    if overview.save_custom_element(block_name, block_title, textile)
      render(partial: "block_textilizable",
            locals: { project: project,
                      block_title: block_title,
                      block_name: block_name,
                      textile: textile })
   else
     render text: t(:error_textile_not_saved), status: 400
   end
  end

  # Add a block to user's page
  # The block is added on top of the page
  # params[:block] : id of the block to add
  def add_block
    block = params[:block]
    if MyProjectsOverviewsController.available_blocks.keys.include? block
      render partial: "block", locals: { block_name: block, editing: true }
    elsif block == "custom_element"
      render_new_custom_block
    else
      render nothing: true
    end
  end

  ##
  # Handle saving the changes
  def save_changes
    # Save block states
    save_blocks_from_params

    if overview.save
      flash[:notice] = I18n.t(:notice_successful_update)
      redirect_to(action: :index)
    else
      flash[:error] = I18n.t(:error_saving_changes,
                             errors: overview.errors.full_messages.join(', '))
      render :page_layout
    end
  end

  def render_attachments
    render partial: 'page_layout_attachments'
  end

  def destroy_attachment
    if user.allowed_to?(:edit_project, project)
      begin
        att = Attachment.find(params[:attachment_id].to_i)
        overview.attachments.delete(att)
        overview.save
      rescue ActiveRecord::RecordNotFound
      end
    end

    render partial: 'page_layout_attachments'
  end

  helper_method :project,
                :user,
                :overview
  def project
    @project
  end

  def user
    current_user
  end

  def overview
    @overview ||= MyProjectsOverview.find_or_create_by(project_id: project.id)
  end

  private

  def render_new_custom_block
    new_block = overview.new_custom_element
    overview.hidden << new_block
    if overview.save
      render(partial: "block_textilizable",
             locals: { project: project,
                       block_title: l(:label_custom_element),
                       new_block: true,
                       block_name: new_block.first,
                       textile: new_block.last })
    else
      render text: I18n.t(:error_saving_changes, errors: overview.errors.full_messages.join(', ')),
                   status: 500
    end
  end

  ##
  # Given params of the form
  # { top: 'block,block,block', ... }
  # Save the actual block positions, filtering the list doing so.
  def save_blocks_from_params
    custom_elements = overview.custom_elements

    %w(top left right hidden).each do |group|
      active_blocks = param_to_blocks(params[group], custom_elements)
      overview.send("#{group}=", active_blocks)
    end
  end

  ##
  # Returns a list of valid blocks for the given group param
  def param_to_blocks(block_str, custom_elements)
    blocks = []
    block_str.split(',').select do |name|
      if MyProjectsOverviewsController.available_blocks.keys.include?(name)
        blocks << name
      else
        custom = custom_elements.detect {|ary| ary.first == name }
        blocks << custom unless custom.nil?
      end
    end

    blocks
  end

  def default_breadcrumb
    l(:label_overview)
  end

  def jump_to_project_menu_item
    if params[:jump]
      # try to redirect to the requested menu item
      redirect_to_project_menu_item(project, params[:jump]) && return
    end
  end
end

app/helpers/my_projects_overviews_helper.rb
#-- copyright
# OpenProject My Project Page Plugin
#
# Copyright (C) 2011-2015 the OpenProject Foundation (OPF)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See doc/COPYRIGHT.md for more details.
#++

module MyProjectsOverviewsHelper

  def top_fields
    %w(top)
  end

  def middle_fields
    %w(left right)
  end

  def hidden_fields
    %w(hidden)
  end

  def blocks
    @blocks ||= {
      'top' => overview.top,
      'left' => overview.left,
      'right' => overview.right,
      'hidden' => overview.hidden
    }
  end

  def grid_field(name)
    css_classes = %w(block-receiver list-position widget-container) + [name]
    data = {
      dragula: name,
      position: name
    }
    construct_blocks(name: name, css_classes: css_classes, data: data)
  end

  def rendered_field(name)
    construct_blocks(name: name, css_classes: Array(name))
  end

  def block_options
    @block_options = [default_selected_option]
    MyProjectsOverviewsController.available_blocks.each do |k, v|
      @block_options << [l("my.blocks.#{v}", default: [v, v.to_s.humanize]), k]
    end
    @block_options << [l(:label_custom_element), :custom_element]
  end

  def childprojects
    @childprojects ||= project.children.visible
  end

  def recent_news
    @news ||= project
              .news
              .includes([:author, :project])
              .order("#{News.table_name}.created_on DESC")
              .limit(5)
  end



  def attachments
    @attachments = overview.attachments || []
  end

  private

  def default_selected_option
    [
      "--- #{t(:actionview_instancetag_blank_option)} ---",
      '',
      { disabled: true, selected: true }
    ]
  end

  def construct_blocks(opts = {})
    name, css_classes, data = [:name, :css_classes, :data].map { |sym| opts.fetch sym, '' }
    content_tag :div, id: "list-#{name}", class: css_classes, data: data do
      ActiveSupport::SafeBuffer.new(blocks[name].map { |b| construct b }.join)
    end
  end

  def block_available?(block)
    controller.class.available_blocks.keys.include? block
  end

  def construct(block)
    if block.is_a? Array
      return render_textilized block
    end
    if block_available? block
      return render_normal block
    end
  end

  def ajax_url(name)
    url_for controller: '/my_projects_overviews',
            action: 'order_blocks',
            group: name
  end

  def render_textilized(block)
    render partial: 'block_textilizable', locals: {
      block_name: block.first,
      block_title: block[1],
      textile: block.last
    }
  end

  def render_normal(block)
    render partial: 'block', locals: { block_name: block }
  end
end

app/views/my_projects_overviews/blocks/_calendar.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% if defined? block_name_id %>
  <%= content_for block_name_id %>
<% end %>

<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-calendar') %>
  <span class="widget-box--header-title"><%=l(:label_calendar)%></span>
</h3>

<%
  calendar = Redmine::Helpers::Calendar.new(Date.today, current_language, :week)
  wps = WorkPackage.table_name

  calendar.events = WorkPackage.visible
    .where(project: current_user.projects)
    .where(
      "
        (#{wps}.start_date >= ? AND #{wps}.start_date <= ?) OR
        (#{wps}.due_date >= ? AND #{wps}.due_date <= ?)
      ",
      calendar.startdt, calendar.enddt, calendar.startdt, calendar.enddt
    )
    .includes(:project, :type, :priority, :assigned_to) unless current_user.projects.empty?
%>

<%= render :partial => 'common/calendar', :locals => {:calendar => calendar } %>

app/views/my_projects_overviews/blocks/_members.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% if defined? block_name_id %>
  <%= content_for block_name_id %>
<% end %>

<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-group') %>
  <span class="widget-box--header-title"><%=t(:label_member_plural)%></span>
</h3>


<% if current_user.allowed_to?(:view_members, project) %>
  <% if @project.members.count > 0 && users_by_role(50).any? %>
    <div class="members overview" id="users_per_role">
      <p>
        <%= render partial: "members",
                  locals: { users_by_role: users_by_role(50),
                              count_users_by_role: count_users_by_role } %>
      </p>
    </div>
  <% end %>
<% else %>
  <div class="members overview">
    <%= t(:label_no_visible_members) %>
  </div>
<% end %>
<% if current_user.allowed_to?(:manage_members, project) %>
  <%#= link_to project_members_path(project_id: project.identifier, show_add_members: true),
        { class: 'button -alt-highlight ml-30',
          title: t(:button_add_member),
          aria: { label: t(:button_add_member) }} do %>
    <%#= op_icon('button--icon icon-add') %>
<!--    <span class="button--text"><%##= t('activerecord.models.member') %></span>-->
  <%# end %>
<% end %>
<% if current_user.allowed_to?(:view_members, project) %>
  <%= link_to project_members_path(project_id: project.identifier),
        { class: 'button -highlight mr-0',
          title: t(:label_view_all_members),
          aria: { label: t(:label_view_all_members) }} do %>
    <%= op_icon('button--icon icon-group') %>
    <span class="button--text"><%= t(:label_view_all_members) %></span>
  <% end %>
<% end %>

app/views/my_projects_overviews/blocks/_milestones_query.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% if defined? block_name_id %>
  <%= content_for block_name_id %>
<% end %>

<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-work-packages') %>
  <span class="widget-box--header-title">Milestones</span>
</h3>

<% query = @project.queries.find_by(name: 'Milestones') %>

<% if query.nil? %>
  Query 'Milestones' not found.
<% else %>
  <%= render partial: 'my_projects_overviews/list_dynamic', locals: { query: query } %>
<% end %>

app/views/my_projects_overviews/blocks/_news_latest.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% if defined? block_name_id %>
  <%= content_for block_name_id %>
<% end %>

<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-news') %>
  <span class="widget-box--header-title"><%=l(:label_news_latest)%></span>
</h3>

<% if recent_news.any? && authorize_for('news', 'index') %>
 <ul class="widget-box--arrow-links news-inner">
    <%= render :partial => 'news/news', :collection => recent_news %>
    <p>
      <%= link_to l(:label_news_view_all),
                  {:controller => 'news',
                  :action => 'index',
                  :project_id => project},
                  :class => 'button -highlight' %>
      <%= link_to new_project_news_path(@project),
            { class: 'button -alt-highlight',
              title: t(:label_news_new),
              aria: { label: t(:label_news_new) }} do %>
          <%= op_icon('button--icon icon-add') %>
          <span class="button--text"><%= l('activerecord.models.news') %></span>
        <% end %>
    </p>
  </ul>
<% end %>

app/views/my_projects_overviews/blocks/_project_description.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% if defined? block_name_id %>
  <%= content_for block_name_id %>
<% end %>

<h3 class="widget-box--header">
  <i class="icon-context icon-news" aria-hidden="true"></i>
  <span class="widget-box--header-title"><%=l(:label_project_description)%></span>
</h3>

<div class="overview">
  <%= format_text @project.description %>
</div>

<% if current_user.allowed_to?(:edit_project, project) %>
  <%= link_to settings_project_path(project), class: 'button -highlight ml-30' do %>
    <%= op_icon('button--icon icon-edit') %>
    <span class="button--text"><%= l(:button_edit) %></span>
  <% end %>
<% end %>

app/views/my_projects_overviews/blocks/_project_details.html.erb
<%#-- copyright
OpenProject My Project Page Plugin
Copyright (C) 2011-2014 the OpenProject Foundation (OPF)
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
See doc/COPYRIGHT.md for more details.
++#%>

<% if defined? block_name_id %>
  <%= content_for block_name_id %>
<% end %>

<h3 class="widget-box--header">
  <i class="icon-context icon-projects" aria-hidden="true"></i>
  <span class="widget-box--header-title"><%=l(:label_subproject_plural)%></span>
</h3>

<div class="overview project_details">
  <ul>
  <% if childprojects.any? %>
    <% @childprojects.each do |p| %>
      <li>
        <%= link_to(h(p), project_url(p)) %>
      </li>
    <% end %>
  <% end %>
  <% project.visible_custom_field_values.each do |custom_value| %>
    <% if !custom_value.value.blank? %>
      <li><%= h(custom_value.custom_field.name) %>: <%=h show_value(custom_value) %></li>
    <% end %>
  <% end %>
  </ul>
</div>

app/views/my_projects_overviews/blocks/_project_status.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% project_status_cf = ProjectCustomField.where("name LIKE 'Project %'").all %>

<%= javascript_tag do %>
  function changeColor(el) {
    if (el.classList.contains('-red')) {
        el.classList.remove('-red');
        el.classList.add('-green');
    } else if (el.classList.contains('-amber')) {
        el.classList.remove('-amber');
        el.classList.add('-red');
    } else if (el.classList.contains('-green')) {
        el.classList.remove('-green');
        el.classList.add('-amber');
    }
  }

  var statusElements = document.getElementsByClassName('project-status');
  for(var i = 0; i < statusElements.length; i++) {
      statusElements[i].addEventListener('click', function(e) {
        changeColor(e.target);
      });
  }
<% end %>

<h3 class="widget-box--header">
  <%= op_icon('icon-context status-reporting') %>
  <span class="widget-box--header-title">Project status</span>
</h3>

<div style="display: flex">
  <div style="flex: 1; border-right: 5px solid transparent;">
    <div class="generic-table--container">
      <div class="generic-table--results-container">
        <table class="generic-table highlighted-table">
          <tbody>
          <% project_status_cf.each do |cf| %>
              <tr>
                <td class="highlighted-cell">
                  <%= cf.name %>:
                </td>
                <td>
                  <%= @project.custom_value_for(cf).formatted_value %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div style="flex: 1; border-left: 5px solid transparent;">
    <div class="generic-table--container">
      <div class="generic-table--results-container">
        <table class="generic-table highlighted-table">
          <tbody>
          <tr>
            <td colspan="3"class="highlighted-cell">
              STATUS
            </td>
          </tr>
          <tr>
            <td colspan="2"class="highlighted-cell">
              Completion [%]:
            </td>
            <td colspan="1">
              <%= @project.custom_value_for(CustomField.find_by(name: 'Completion')).formatted_value rescue 'xxx' %>
            </td>
          </tr>
          <tr>
            <td class="highlighted-cell -centered">Time</td>
            <td class="highlighted-cell -centered">Budget</td>
            <td class="highlighted-cell -centered">Quality</td>
          </tr>
          <tr>
            <td class="project-status-cell">
              <span class="project-status -red"></span>
            </td>
            <td class="project-status-cell">
              <span class="project-status -amber"></span>
            </td>
            <td class="project-status-cell">
              <span class="project-status -green"></span>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/my_projects_overviews/blocks/_spent_time.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% if defined? block_name_id %>
  <%= content_for block_name_id %>
<% end %>

<h3 class="widget-box--header">
  <%= op_icon('icon-context icon-time') %>
  <span class="widget-box--header-title"><%=l(:label_spent_time)%> (<%= l(:label_last_n_days, 7) %>)</span>
</h3>

<%
   entries = TimeEntry
             .includes([:activity, :project, {:work_package => [:type, :status]}])
             .visible(User.current)
             .where(project_id: @project.id)
             .where(["#{TimeEntry.table_name}.spent_on BETWEEN ? AND ?", Date.today - 6, Date.today]).references(:projects)
             .order("#{TimeEntry.table_name}.spent_on DESC, #{Project.table_name}.name ASC, #{Type.table_name}.position ASC, #{WorkPackage.table_name}.id ASC")
   entries_by_day = entries.group_by(&:spent_on)
%>

<div class="total-hours">
  <p><%= l(:label_total) %>: <%= html_hours("%.2f" % entries.sum(:hours).to_f) %></p>
</div>

<% if entries.any? %>
  <div class="generic-table--container">
    <div class="generic-table--results-container">
      <table class="generic-table time-entries">
        <colgroup>
          <col highlight-col>
          <col highlight-col>
          <col highlight-col>
          <col highlight-col>
          <col>
        </colgroup>
        <thead>
          <tr>
            <th>
              <div class="generic-table--header-outer">
                <div class="generic-table--header">
                  <span>
                    <%= l(:label_activity) %>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--header-outer">
                <div class="generic-table--header">
                  <span>
                    <%= Project.model_name.human %>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--header-outer">
                <div class="generic-table--header">
                  <span>
                    <%= TimeEntry.human_attribute_name(:comments) %>
                  </span>
                </div>
              </div>
            </th>
            <th>
              <div class="generic-table--header-outer">
                <div class="generic-table--header">
                  <span>
                    <%= TimeEntry.human_attribute_name(:hours) %>
                  </span>
                </div>
              </div>
            </th>
            <th><div class="generic-table--empty-header"></div></th>
          </tr>
        </thead>
        <tbody>
        <% entries_by_day.keys.sort.reverse.each do |day| %>
            <tr>
              <td><strong><%= day == Date.today ? l(:label_today).titleize : format_date(day) %></strong></td>
              <td ></td>
              <td ></td>
              <td class="hours"><em><%= html_hours("%.2f" % entries_by_day[day].sum(&:hours).to_f) %></em></td>
              <td class="-short"></td>
            </tr>
            <% entries_by_day[day].each do |entry| -%>
                <tr class="time-entry" style="border-bottom: 1px solid #f5f5f5;">
                  <td class="activity"><%=h entry.activity %></td>
                  <td class="subject"><%=h entry.project %> <%= ' - '.html_safe + link_to_work_package(entry.work_package, :truncate => 50) if entry.work_package%></td>
                  <td class="comments"><%=h entry.comments %></td>
                  <td class="hours"><%= html_hours("%.2f" % entry.hours) %></td>
                  <td class="buttons -short">
                    <% if entry.editable_by?(user) -%>
                      <%= link_to icon_wrapper('icon-context icon-edit', t(:button_edit)),
                                  {:controller => '/timelog', :action => 'edit', :id => entry},
                                  :alt => l(:button_edit),
                                  :class => 'no-decoration-on-hover',
                                  :title => l(:button_edit) %>
                      <%= link_to icon_wrapper('icon-context icon-delete', t(:button_delete)),
                                  {:controller => '/timelog', :action => 'destroy', :id => entry},
                                  :confirm => l(:text_are_you_sure),
                                  :method => :delete,
                                  :class => 'no-decoration-on-hover',
                                  :alt => l(:button_delete),
                                  :title => l(:button_delete) %>
                    <% end -%>
                  </td>
                </tr>
            <% end -%>
        <% end -%>
        </tbody>
      </table>

    </div>
  </div>
<% end %>

app/views/my_projects_overviews/blocks/_subprojects.html.erb
<%#-- copyright
OpenProject My Project Page Plugin

Copyright (C) 2011-2014 the OpenProject Foundation (OPF)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License version 3.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

See doc/COPYRIGHT.md for more details.

++#%>

<% if defined? block_name_id %>
  <%= content_for block_name_id %>
<% end %>

<h3 class="widget-box--header">
  <i class="icon-context icon-projects" aria-hidden="true"></i>
  <span class="widget-box--header-title"><%=l(:label_subproject_plural)%></span>
</h3>

<% if childprojects.any? %>
  <div class="subprojects overview">
    <p>
      <%= childprojects.collect{ |p| link_to(h(p), project_url(p)) }.join(", ").html_safe %>
    </p>
  </div>
<% end %>